/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IEvents, IEventsInterface } from "../IEvents";

const _abi = [
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IEventsInterface {
    return new utils.Interface(_abi) as IEventsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEvents {
    return new Contract(address, _abi, signerOrProvider) as IEvents;
  }
}
