/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IJurisdiction, IJurisdictionInterface } from "../IJurisdiction";

const _abi = [
  {
    inputs: [],
    name: "join",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "leave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IJurisdiction__factory {
  static readonly abi = _abi;
  static createInterface(): IJurisdictionInterface {
    return new utils.Interface(_abi) as IJurisdictionInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IJurisdiction {
    return new Contract(address, _abi, signerOrProvider) as IJurisdiction;
  }
}
